// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PageDocumentDataSlicesSlice = never;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type PublicCreditSimulatorDocumentDataSlicesSlice =
  | InputNumberSlice
  | LoanDetailsSlice
  | LegalSlice;

/**
 * Content for Public credit simulator documents
 */
interface PublicCreditSimulatorDocumentData {
  /**
   * title field in *Public credit simulator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: public_credit_simulator.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *Public credit simulator*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: public_credit_simulator.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  subtitle: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Public credit simulator*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: public_credit_simulator.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PublicCreditSimulatorDocumentDataSlicesSlice>;
}

/**
 * Public credit simulator document from Prismic
 *
 * - **API ID**: `public_credit_simulator`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PublicCreditSimulatorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PublicCreditSimulatorDocumentData>,
    "public_credit_simulator",
    Lang
  >;

export type AllDocumentTypes = PageDocument | PublicCreditSimulatorDocument;

/**
 * Primary content in *InputNumber → Default → Primary*
 */
export interface InputNumberSliceDefaultPrimary {
  /**
   * label field in *InputNumber → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: input_number.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * default value field in *InputNumber → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: input_number.default.primary.default_value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  default_value: prismic.KeyTextField;

  /**
   * placeholder field in *InputNumber → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: input_number.default.primary.placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  placeholder: prismic.KeyTextField;

  /**
   * helper text field in *InputNumber → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: input_number.default.primary.helper_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  helper_text: prismic.KeyTextField;
}

/**
 * Default variation for InputNumber Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InputNumberSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InputNumberSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *InputNumber*
 */
type InputNumberSliceVariation = InputNumberSliceDefault;

/**
 * InputNumber Shared Slice
 *
 * - **API ID**: `input_number`
 * - **Description**: InputNumber
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InputNumberSlice = prismic.SharedSlice<
  "input_number",
  InputNumberSliceVariation
>;

/**
 * Primary content in *Legal → Default → Primary*
 */
export interface LegalSliceDefaultPrimary {
  /**
   * CAT field in *Legal → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.default.primary.cat
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cat: prismic.KeyTextField;

  /**
   * calculation date field in *Legal → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal.default.primary.calculation_date
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  calculation_date: prismic.KeyTextField;
}

/**
 * Default variation for Legal Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LegalSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LegalSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Legal*
 */
type LegalSliceVariation = LegalSliceDefault;

/**
 * Legal Shared Slice
 *
 * - **API ID**: `legal`
 * - **Description**: Legal
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LegalSlice = prismic.SharedSlice<"legal", LegalSliceVariation>;

/**
 * Primary content in *LoanDetails → Default → Primary*
 */
export interface LoanDetailsSliceDefaultPrimary {
  /**
   * title field in *LoanDetails → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: loan_details.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * fee field in *LoanDetails → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: loan_details.default.primary.fee
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  fee: prismic.KeyTextField;

  /**
   * term field in *LoanDetails → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: loan_details.default.primary.term
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  term: prismic.KeyTextField;

  /**
   * rate field in *LoanDetails → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: loan_details.default.primary.rate
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  rate: prismic.KeyTextField;

  /**
   * commission field in *LoanDetails → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: loan_details.default.primary.commission
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  commission: prismic.KeyTextField;
}

/**
 * Default variation for LoanDetails Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LoanDetailsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LoanDetailsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LoanDetails*
 */
type LoanDetailsSliceVariation = LoanDetailsSliceDefault;

/**
 * LoanDetails Shared Slice
 *
 * - **API ID**: `loan_details`
 * - **Description**: LoanDetails
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LoanDetailsSlice = prismic.SharedSlice<
  "loan_details",
  LoanDetailsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PublicCreditSimulatorDocument,
      PublicCreditSimulatorDocumentData,
      PublicCreditSimulatorDocumentDataSlicesSlice,
      AllDocumentTypes,
      InputNumberSlice,
      InputNumberSliceDefaultPrimary,
      InputNumberSliceVariation,
      InputNumberSliceDefault,
      LegalSlice,
      LegalSliceDefaultPrimary,
      LegalSliceVariation,
      LegalSliceDefault,
      LoanDetailsSlice,
      LoanDetailsSliceDefaultPrimary,
      LoanDetailsSliceVariation,
      LoanDetailsSliceDefault,
    };
  }
}
