// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  input_number: dynamic(() => import("./InputNumber")),
  legal: dynamic(() => import("./Legal")),
  rich_text: dynamic(() => import("./RichText")),
  loan_details: dynamic(() => import("./LoanDetails")),
};
