// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  legal: dynamic(() => import("./Legal")),
  rich_text: dynamic(() => import("./RichText")),
};
