// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  features: dynamic(() => import("./Features")),
  hero: dynamic(() => import("./Hero")),
  input_number: dynamic(() => import("./InputNumber")),
  legal: dynamic(() => import("./Legal")),
  loan_details: dynamic(() => import("./LoanDetails")),
};
